# frontend/Dockerfile
FROM node:22-alpine as build
WORKDIR /app

COPY cyber-sentinel/package*.json ./
RUN npm install

COPY cyber-sentinel/ ./
RUN npm run build --prod

FROM nginx:alpine
# Borra el contenido por defecto de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia el build de Angular
COPY --from=build /app/dist/cyber-sentinel/browser/ /usr/share/nginx/html/

EXPOSE 80
